workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
          cd ios
          pod install
    artifacts:
      - build/ios/ipa/*.ipa
