name: mapper
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_database: ^11.0.0
  firebase_auth: ^5.4.2
  percent_indicator: ^4.2.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  
  fonts:
    - family: Ultra
      fonts:
        - asset: assets/fonts/Ultra-Regular.ttf
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
    - assets/images/svg_maps/
