platform :ios, '16.2'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'


project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
